mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name='enquetes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/',
        views.DetalhesView.as_view(), name='detalhes'),

    path('<int:pk>/resultado/',
        views.ResultadoView.as_view(), name='resultado'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls'))
]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
    texto = models.CharField(max_length=150)
    data_pub = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        return self.data_pub >= timezone.now() - datetime.timedelta(hours=24)

class Alternativa(models.Model):
    texto = models.CharField(max_length=50)
    quant_votos = models.IntegerField('Quantidade de votos', default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

mysite/enquetes/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views import View
from .models import Pergunta, Alternativa

class IndexView(View):
    def get(self, request, *arg, **kwargs):
        lista = Pergunta.objects.order_by('-data_pub')
        contexto = {'pergunta_list': lista}
        return render(request, 'enquetes/index.html', contexto)

class DetalhesView(View):
    def get(self, request, *arg, **kwargs):
       pergunta_id=kwargs['pk']
       enquete = get_object_or_404(Pergunta, pk=pergunta_id)
       return render(
           request, 'enquetes/detalhes.html',{'pergunta':enquete})
    def post(self, request, *args, **kwargs):
        pergunta_id=kwargs['pk']
        pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
        try:
            id_votado = request.POST['escolha']
            alt_selecionada = pergunta.alternativa_set.get(pk=id_votado)
        except(KeyError, Alternativa.DoesNotExist):
            contexto = {'pergunta':pergunta, 'erro': 'Escolha uma alternativa válida!',}
            return render(request, 'enquetes/detalhes.html', contexto)
        else:
            alt_selecionada.quant_votos += 1
            alt_selecionada.save()
            return HttpResponseRedirect(reverse('enquetes:resultado', args=(pergunta_id,)))


class ResultadoView(View):
    def get(self, request, *args, **kwargs):
        pergunta_id=kwargs['pk']
        enquete = get_object_or_404(Pergunta, pk=pergunta_id)
        return render(
            request, 'enquetes/resultado.html',{'pergunta':enquete})

"""
INDEX V1.0
def index(request):
    def index(request):
    return HttpResponse("Bem vindo a aplicação de <b>Enquetes<b> Aeeeeeeeeeeeeee")

INDEX V2.0
def index(request):
    lista = Pergunta.objects.all()
    resposta = '<br>'.join([p.texto for p in lista])
    return HttpResponse(resposta)

INDEX V3.0
def index(request):
    lista = Pergunta.objects.order_by('-data_pub')
    contexto = {'lista_enquetes': lista}
    return render(request, 'enquetes/index.html', contexto)

INDEX V4.0
class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_pub')

RESULTADO V1.0
def resultado(request, pergunta_id):
    enquete = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'enquetes/resultado.html',{'pergunta':enquete})

DETALHES V1.0
def detalhes(request, pergunta_id):
    resultado = 'DETALHES da Enquete #%s'
    return HttpResponse(resultado % pergunta_id)

DETALHES V3.0
class DetalhesView(generic.DetailView):
    model = Pergunta


VOTAÇÃO V1.0
def votacao(request, pergunta_id):
    resultado = 'VOTAÇÃO da Enquete #%s'
    return HttpResponse(resultado % pergunta_id)
"""

mysite/enquetes/templates/enquetes/detalhes.html
<html>
    <head>
        <title>Enquetes App</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes</h1>
        <h3>Detalhes da Enquete #{{ pergunta.id }}</h3>
        <h3>{{ pergunta.texto }}</h3>
        <p>Data de publicação: {{ pergunta.data_pub }}</p>
        {% if erro %}
            <hr/>
            <p><b>{{ erro }}</b></p>
            <hr/>
        {% endif %}
        <p>Alternativas possíveis:</p>
        <form method="post"
              action="{% url 'enquetes:detalhes' pergunta.id %}" >
            {% csrf_token %}
        <ul>
            {% for alt in pergunta.alternativa_set.all %}
                <li>
                    <input id="alt{{ forloop.counter }}" type="radio"
                         name="escolha" value="{{ alt.id }}"/>
                    <label for="alt{{ forloop.counter }}">
                    {{ alt.texto }}
                    </label>
                </li>
            {% endfor %}
        </ul>
        <input type="submit" value="Registre seu voto"/>
        </form>
        <hr/>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
    </body>
</html>

mysite/enquetes/templates/enquetes/index.html
{% load static %}
<html>
    <head>
        <title>Enquetes App</title>
        <link rel="stylesheet" type="text/css"
                href="{% static '/enquetes/css/style.css' %}"/>
    </head>
    <body>
        <h1>Aplicação de Enquetes</h1>
        <img width="100" src="{% static 'enquetes/img/logo.jpg' %}" />
        <h3>Lista das enquetes cadastradas:</h3>
        {% if pergunta_list %}
            <ol>
                {% for p in pergunta_list %}
                    <li>
                        <a href="{% url 'enquetes:detalhes' p.id %}">
                        {{ p.texto }}</a>&nbsp;&nbsp;
                        (<a href="{% url 'enquetes:resultado' p.id %}">Ver parcial</a>)
                    </li>
                {% endfor %}
            </ol>
        {% else %}
            <p>Nenhuma enquete cadastrada!</p>
        {% endif %}
        <hr/>
        &copy;DSWeb/TADS/CNAT/IFRN - 2024.
    </body>
</html>

mysite/enquetes/templates/enquetes/resultado.html
<html>
    <head>
        <title>Enquetes App</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes</h1>
        <h3>Resultado parcial da Enquete #{{ pergunta.id }}</h3>
        <h3>{{ pergunta.texto }}</h3>
        <p>Data de publicação: {{ pergunta.data_pub | date:"d/m/y, H:i" }}hs</p>
        <p>Alternativas possíveis:</p>

        <ul>
            {% for alt in pergunta.alternativa_set.all %}
                <li>
                    {{ alt.texto }} === {{alt.quant_votos }}
                    voto{{ alt.quant_votos | pluralize }}
                    </label>
                </li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
        | <a href="{% url 'enquetes:detalhes' pergunta.id %}">Votar novamente</a>
    </body>
</html>